# @package _global_

defaults:
  - pointnav_depth_base
  - /habitat/dataset/pointnav: beacon
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            type: HabitatSimRGBSensor
            height: 256
            width: 256
            position:
              - 0.0
              - 1.25
              - 0.0
            orientation:
              - 0.0
              - 0.0
              - 0.0
            hfov: 90
            sensor_subtype: PINHOLE
            noise_model: None
            noise_model_kwargs: { }
    habitat_sim_v0:
      gpu_gpu: true
      allow_sliding: false
