# @package _global_

defaults:
  - pointnav_depth_base
  - /habitat/dataset/pointnav: beacon
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
    habitat_sim_v0:
      gpu_gpu: true
      allow_sliding: false
