# @package _global_

defaults:
  - pointnav_depth_base
  - /habitat/dataset/pointnav: beacon
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          depth_sensor:
            width: 256
            height: 256
            normalize_depth: True     
            position: [0.03, 0.55, 0.0]
            orientation: [-0.2, 0.0, 0.0]
            hfov: 80
    habitat_sim_v0:
      gpu_gpu: false
      allow_sliding: false
